### ISSUE TITLE
IDE: make jcr_root directory configurable

### ISSUE THREAD

**Issue by bobi** [DmytroTroynikov/aemtools#115]
Currently this plugin works only under jcr_root directory, please make this directory configurable, as we are using another directory in our project

**Comment by dmitry-cherkas** [comment]
Hi @bobi,

Could you please share your project directory structure skeleton to give us better understanding of your use case?

**Comment by bobi** [comment]
structure is similar to regular structure, but root folder called "content" instead of "jcr_root" and its pretty complex to rename it in more than 50 maven modules

**Comment by DmytroTroynikov** [comment]
Hello @bobi, @dmitry-cherkas,

I propose following solution:

The `jcr_root` is the default method of recognition and will remain as default in future.
Additionally, ability to mark any other directory as `HTL Root` will be provided via new action `Mark Directory as -> HTL Root`.

This will allow to address the use case.

**Comment by bobi** [comment]
this will be good solution

**Comment by DmytroTroynikov** [comment]
Hi @bobi ,

We've released [0.8.1 beta.](https://github.com/DmytroTroynikov/aemtools/releases/tag/v0.8.1-beta1) with the feature, could you please check it?

**Comment by bobi** [comment]
it works, thank you
