### ISSUE TITLE
OSGI: Add ability to generate SCR xml from OSGI annotations during build by Idea

### ISSUE THREAD

**Issue by bobi** [DmytroTroynikov/aemtools#226]
I think it will be useful if Idea will be able to generate scr xml from OSGI annotations during build by IDE.
It will be useful for build and then run unit tests with IDE.

**Comment by koha26** [comment]
Thank you for the suggestion. However, I think it is not the responsibility of the plugin. Doesn't this maven plugin (https://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/apache-felix-maven-scr-plugin-use.html) do it?

**Comment by bobi** [comment]
yes, this plugin or [maven-bundle-plugin](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html)
if this is out of scope in this plugin then you can close the ticket.

**Comment by koha26** [comment]
I just want to figure it out for myself. What are the use cases when such plugin functionality can be used instead of maven-scr-plugin or maven-bundle-plugin?

**Comment by bobi** [comment]
mine use case is to build project with IDE and then run tests again with IDE not with maven.

**Comment by koha26** [comment]
Unfortunately, a lot of AEM projects use Maven as a build tool for projects. So, I will close this issue, because there is existed free workaround.
