### ISSUE TITLE
HTL: default 'properties' object does not recognize custom fields.

### ISSUE THREAD

**Issue by pabpalac** [DmytroTroynikov/aemtools#241]
![image](https://github.com/aemtools/aemtools/assets/25589447/f4883e1c-8a97-4d04-a6c7-5ad2b2948ba9)

The following screenshot is from an OOTB aem archetype. as you can see. The IDE is marking a syntax error with the 'properties.text' because it does not recognize the custom field. (Unresolved reference: 'text').

**Comment by koha26** [comment]
@pabpalac Do you mean that HTL doesn't resolve dialog value 'text' from `core/wcm/components/text/v2/text`?
Is your current script from the proxy text component?

**Comment by pabpalac** [comment]
This is the OOTB hello world component. The issue  is that the plugin is marking this as an error but is not.

This is the expected behavior (from another computer with an older version of the IntelliJ 2022.3.2).

![image](https://github.com/aemtools/aemtools/assets/25589447/6cff92ec-95c6-438b-9f7c-4624c034d014)

It is happening in Intellij 2023.1.2.

![image](https://github.com/aemtools/aemtools/assets/25589447/6679088d-642a-4719-a0b8-b404b45bfaac)

**Comment by koha26** [comment]
Got it, thank you for reporting this issue. Could you please hover the mouse on the 'text' property and will send me what is shown?

**Comment by pabpalac** [comment]
Sure!

![image](https://github.com/aemtools/aemtools/assets/25589447/d15e88f1-ac8b-4e3e-bb8a-3807153c1f04)

**Comment by koha26** [comment]
Another one ask: show the `.content.xml` of this component, please.

**Comment by pabpalac** [comment]
Here's the component xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="cq:Component"
          jcr:title="Hello World Component"
          componentGroup="Sorcery - Content"/>
```


Here's the component's dialog xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0"
          xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
          jcr:primaryType="nt:unstructured"
          jcr:title="Properties"
          sling:resourceType="cq/gui/components/authoring/dialog">
    <content
            jcr:primaryType="nt:unstructured"
            sling:resourceType="granite/ui/components/coral/foundation/fixedcolumns">
        <items jcr:primaryType="nt:unstructured">
            <column
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="granite/ui/components/coral/foundation/container">
                <items jcr:primaryType="nt:unstructured">
                    <text
                            jcr:primaryType="nt:unstructured"
                            sling:resourceType="granite/ui/components/coral/foundation/form/textfield"
                            fieldLabel="Text"
                            name="./text"/>
                </items>
            </column>
        </items>
    </content>
</jcr:root>
```

**Comment by koha26** [comment]
Thank you. The dialog file name is dialog.xml or _cq_dialog.xml?

**Comment by pabpalac** [comment]
the dialog file name is .content.xml

![image](https://github.com/aemtools/aemtools/assets/25589447/922dd316-6280-460a-8f95-a11dbbb80e47)

**Comment by koha26** [comment]
Thank you a lot for all info. Will update you later.

**Comment by pabpalac** [comment]
This is now resolved. The issue was that the IntelliJ hasn't any JDK configured. By setting up an SDK the problem was fixed.
