### ISSUE TITLE
Not compatible with IntelliJ 2023.2

### ISSUE THREAD

**Issue by csaboka** [DmytroTroynikov/aemtools#243]
Similarly to #235 and #237, a new IDEA version has recently become available and this plugin won't work with it:
![image](https://github.com/aemtools/aemtools/assets/2852084/357f203b-b272-4f22-9629-5ac53b91c740)
Can we get an update, please, so we can keep using this plugin with the latest IDE version?

**Comment by koha26** [comment]
Thank you for this issue. I am sorry for inconvenience. I've already created PR to fix it. It will be fixed soon.

**Comment by koha26** [comment]
Hi @csaboka, version [v1.0.1](https://plugins.jetbrains.com/plugin/9397-aem-tools/versions/stable/369696) has been uploaded to market.
