### ISSUE TITLE
Not compatible with IntelliJ 2024.2

### ISSUE THREAD

**Issue by csaboka** [DmytroTroynikov/aemtools#253]
Similarly to https://github.com/aemtools/aemtools/issues/243 and https://github.com/aemtools/aemtools/issues/246, a new IDEA version has recently become available and this plugin won't work with it:
![image](https://github.com/user-attachments/assets/a0d80ef7-1283-4c05-9328-0241100d67bb)
Can we please get an update, please, so we can keep using this plugin with the latest IDE version?

**Comment by koha26** [comment]
Hi @csaboka, thank you for letting me know. I will fix it as soon as possible.

**Comment by csaboka** [comment]
Thank you for the quick fix! I can confirm it's working with the latest IntelliJ version.
