### ISSUE TITLE
HTL: Reference on inherited methods of model does not working

### ISSUE THREAD

**Issue by dlyahov** [DmytroTroynikov/aemtools#53]
I have model

```
@Model
class MyModel {
   protected String getName() {
        return "str";
   }
}
```

and have inherited class from this model

```
@Model
class MyChildModel extends MyModel {
}
```

and in `html` file I define `MyChildModel `and I want use inherited method

```
<sly data-sly-use.model="MyChildModel">
    <p>model.name</p>
</sly>
```
Action: I try go to defining of method via `Ctrl + Click` on `name`.

Expected: I go to declaration of this method.
Actual: Nothing happens

**Comment by DmytroTroynikov** [comment]
Could you please provide more details about actual method name and signature?

**Comment by dlyahov** [comment]
Issue is wrong because in sightly we cannot get protected method from ancestor class.
