### ISSUE TITLE
HTML: Cannot resolve model class

### ISSUE THREAD

**Issue by dmitry-cherkas** [DmytroTroynikov/aemtools#96]
Looks like plugin interferes with IDE ReferenceProviders, and prevents them from resolving class references inside data-sly-use statements:

![image](https://user-images.githubusercontent.com/3441528/27158089-b6754618-516d-11e7-829c-0bde0cb8f735.png)

**Comment by DmytroTroynikov** [comment]
Hello @dmitry-cherkas, could you please check if the bug is reproduced via EL use (in your case it would be ```data-sly-use.model="${'com.models.CompanyFactsModel'}```), and apply the fix to corresponding reference provider (`com.aemtools.reference.htl.provider.DataSlyUseElReferenceProvider`)

Thanks
